### TODO 初始化压测数据
POST http://127.0.0.1:8002/api/inventory/initMeasureData
Content-Type: application/json

[
    "skuCode1",
    "skuCode2",
    "skuCode3",
    "skuCode4",
    "skuCode5",
    "skuCode6",
    "skuCode7",
    "skuCode8",
    "skuCode9",
    "skuCode10",
    "skuCode11",
    "skuCode12",
    "skuCode13",
    "skuCode14",
    "skuCode15",
    "skuCode16",
    "skuCode17",
    "skuCode18",
    "skuCode19",
    "skuCode20",
    "skuCode21",
    "skuCode22",
    "skuCode23",
    "skuCode24",
    "skuCode25",
    "skuCode26",
    "skuCode27",
    "skuCode28",
    "skuCode29",
    "skuCode30",
    "skuCode31",
    "skuCode32",
    "skuCode33",
    "skuCode34",
    "skuCode35",
    "skuCode36",
    "skuCode37",
    "skuCode38",
    "skuCode39",
    "skuCode40",
    "skuCode41",
    "skuCode42",
    "skuCode43",
    "skuCode44",
    "skuCode45",
    "skuCode46",
    "skuCode47",
    "skuCode48",
    "skuCode49",
    "skuCode50",
    "skuCode51",
    "skuCode52",
    "skuCode53",
    "skuCode54",
    "skuCode55",
    "skuCode56",
    "skuCode57",
    "skuCode58",
    "skuCode59",
    "skuCode60",
    "skuCode61",
    "skuCode62",
    "skuCode63",
    "skuCode64",
    "skuCode65",
    "skuCode66",
    "skuCode67",
    "skuCode68",
    "skuCode69",
    "skuCode70",
    "skuCode71",
    "skuCode72",
    "skuCode73",
    "skuCode74",
    "skuCode75",
    "skuCode76",
    "skuCode77",
    "skuCode78",
    "skuCode79",
    "skuCode80",
    "skuCode81",
    "skuCode82",
    "skuCode83",
    "skuCode84",
    "skuCode85",
    "skuCode86",
    "skuCode87",
    "skuCode88",
    "skuCode89",
    "skuCode90",
    "skuCode91",
    "skuCode92",
    "skuCode93",
    "skuCode94",
    "skuCode95",
    "skuCode96",
    "skuCode97",
    "skuCode98",
    "skuCode99",
    "skuCode100"
]
